### ISSUE TITLE
createInstance() missing documentDeliveryType parameter

### ISSUE THREAD

**Issue by erosiec** [hellosign/helloworks-nodejs-sdk#14]
The createInstance() method does not include a documentDeliveryType parameter. 

When **documentDelivery:true** the only available delivery method is an email attachment, blocking the ability to send completed documents to participants as a link.

**Comment by behr-davide** [comment]
I opened a [pull request](https://github.com/hellosign/helloworks-nodejs-sdk/pull/13) to add support for this feature. Could someone link it to this issue? The CI pipeline failed and I suspect it is because I do not have the ability to specify configuration values required to run the tests.
