### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by connorwinston** [hellosign/helloworks-nodejs-sdk#8]
Hello,

I am running into this error and it seems vague to me and I can not figure out what it means, any help would be great!

```
Error
at response.json.then (/var/task/node_modules/helloworks-sdk/lib/helloworks.js:137:22)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by nathanbuchar** [comment]
Looks like I'm expecting JSON code from the back end but that's not what I'm actually getting. Which API call are you making?

**Comment by pietgeursen** [comment]
I see this intermittently too when making calls to `workflowInstances.createInstance`

**Comment by connorwinston** [comment]
I am also using createInstance when getting these errors, out of 40ish calls it errors around 5-3 times. I have a set of data I am iterating through and it happens on different ones each time.

**Comment by Framinus** [comment]
@ConMan2102 and @pietgeursen - Thank you for reporting this! Can you email apisupport at hellosign.com so that we can create some internal tracking around this issue? In the meantime, I'll do some testing and see if I can replicate this behavior.

**Comment by nathanbuchar** [comment]
Thanks for hopping on this @Framinus !
