### ISSUE TITLE
Metadata fields are broken when Helloworks calls back.

### ISSUE THREAD

**Issue by pietgeursen** [hellosign/helloworks-nodejs-sdk#9]
When receiving a callback from Helloworks, the metadata object looks like:

```json
{"email,piet@opencollective.com":"0","year,2019":"1"}
```

When I'm sending:
```json
{
"email": "piet@opencollective.com",
"year": "2019"
}
```
Using version 1.1.0

**Comment by nathanbuchar** [comment]
@Framinus will you be able to take a look at this one as well? Seems the HelloWorks endpoint isn't returning data in the expected format. I.e. `{ "key,value": "i" }` instead of `{ "key": "value" }`. This might be an issue on HW's side.

**Comment by nathanbuchar** [comment]
@pietgeursen, which endpoint are you trying to hit?

**Comment by pietgeursen** [comment]
> which endpoint are you trying to hit?

`workflowInstances.createInstance`

---

I haven't spent any time trying to debug _why_, but if I use [this fork](https://github.com/pietgeursen/helloworks-nodejs-sdk) I don't seem to have this problem.

**Comment by nathanbuchar** [comment]
Roger that, we'll do some digging and get back to you :)

**Comment by latoyazamill** [comment]
@pietgeursen Thank you for reporting this! Can you email apisupport at hellosign.com so that we can create some internal tracking around this issue? In the meantime, we'll do some testing and see if we can replicate this behavior.

**Comment by znarf** [comment]
The bug is not in the SDK because we're reading directly from the Helloworks callback. I opened a support request for that problem.

**Comment by znarf** [comment]
The PR https://github.com/hellosign/helloworks-nodejs-sdk/pull/5 from @pietgeursen was not properly handled,

His code was https://github.com/hellosign/helloworks-nodejs-sdk/pull/5/files:

```
if(opts.metadata) {
  Object.entries(opts.metadata).forEach(([key, value]) => {
```

And you merged it as https://github.com/hellosign/helloworks-nodejs-sdk/pull/6/files:

```
if (opts.metadata) {
  Object.entries(opts.metadata).forEach((key, value) => {
```

Huge difference. Please fix it and release a new version!

**Comment by nathanbuchar** [comment]
Whoops! Silly mistake. Thanks for reporting, I'll get this in today. Sorry for the delay on it.
